### ISSUE TITLE
Incorrect path for mali driver source

### ISSUE THREAD

**Issue by PhilipDeegan** [Miouyouyou/MyyQi-kernel#1]
The link is now:

```
https://developer.arm.com/-/media/Files/downloads/mali-drivers/kernel/mali-midgard-gpu/TX011-SW-99002-r14p0-01rel0.tgz
```

**Comment by Miouyouyou** [comment]
Thanks for your report. I'll modify the script.

That said, this repository is not maintained anymore. (´・ω・`　)
I'll update the README in consequence though.

The latest maintained version of [**MyyQi**](https://github.com/Miouyouyou/MyyQi) is here : https://github.com/Miouyouyou/MyyQi
Which provide 4.12.0 kernel including the latest Mali Midgard r17p0 drivers using the correct URL.

Starting from the 4.13.0-rc1 version, I split up the repositories in two, with the scripts and patches in [**RockMyy**](https://github.com/Miouyouyou/RockMyy), and the builds themselves in **[RockMyy-Build](https://github.com/Miouyouyou/RockMyy-Build)**.
